version: '2'
services:
  serverapp:
    build: ./server
    command: node server.js
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3412:3412"
    
  web:
    build: .
    command: node index.js
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - serverapp
